/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.Admin_BestFit;
import Clases.Admin_FirstFit;
import Clases.Admin_WorstFit;
import Controlador.Controlador;
import java.awt.Color;
import javax.swing.JLabel;
import java.util.HashMap; // import the HashMap class
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author josep
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    HashMap<Integer, int[]> colores;
    Controlador controler;
    public GUI() throws InterruptedException {
        initComponents();
        colores = new HashMap<Integer, int[]>();
        controler = new Controlador();
        controler.start();
            new Thread(){
        @Override
        public void run() {
                inicio();
        };
            }.start();
       //run();
        
        
        //bestFit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane2.setViewportView(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane3.setViewportView(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane4.setViewportView(jPanel4);

        jLabel1.setText("BestFit");

        jLabel2.setText("FirstFit");

        jLabel3.setText("WorstFit");

        jLabel4.setText("Buddy System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void inicio(){
        
  
        while(true){
            try {
                TimeUnit.SECONDS.sleep(1);
            } catch (InterruptedException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            bestFit(this.controler.getBestFit());
            firstFit(this.controler.getFirstFit());
            worstFit(this.controler.getWorstFit());
        }
    
    }
    
    
    
    public  void bestFit(Admin_BestFit bestFit){
        this.jPanel1.removeAll();
        int memoria[]=bestFit.getMemoria();
        
        for (int i = 0; i < memoria.length; i++) {
            if (memoria[i]== -1) {
                JLabel etiqueta=new JLabel();
                etiqueta.setHorizontalAlignment(JLabel.CENTER);
                etiqueta.setBackground(Color.white);
                etiqueta.setOpaque(true);
                this.jPanel1.add(etiqueta);
            }else{
                if(colores.get(memoria[i])!= null){
                    int [] tempColor = colores.get(memoria[i]);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel1.add(etiqueta);
                }else{
                    int tempColor[] = generateColor();
                    colores.put(memoria[i], tempColor);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel1.add(etiqueta);
                }
            }
            
        }
        this.jPanel1.updateUI();
        this.jPanel1.repaint();
    }
    
    
    
    
    public void firstFit(Admin_FirstFit firstFit){
        this.jPanel2.removeAll();
        int memoria[]=firstFit.getMemoria();
        for (int i = 0; i < memoria.length; i++) {
            if (memoria[i]== -1) {
                JLabel etiqueta=new JLabel();
                etiqueta.setHorizontalAlignment(JLabel.CENTER);
                etiqueta.setBackground(Color.white);
                etiqueta.setOpaque(true);
                this.jPanel2.add(etiqueta);
            }else{
                if(colores.get(memoria[i])!= null){
                    int [] tempColor = colores.get(memoria[i]);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel2.add(etiqueta);
                }else{
                    int tempColor[] = generateColor();
                    colores.put(memoria[i], tempColor);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel2.add(etiqueta);
                }
            }
            
        }
        this.jPanel2.updateUI();
         this.jPanel2.repaint();
    }
    
    
    
    
    public void worstFit(Admin_WorstFit worstFit){
        this.jPanel3.removeAll();
        int memoria[]= worstFit.getMemoria();
        for (int i = 0; i < memoria.length; i++) {
            if (memoria[i]== -1) {
                JLabel etiqueta=new JLabel();
                etiqueta.setHorizontalAlignment(JLabel.CENTER);
                etiqueta.setBackground(Color.white);
                etiqueta.setOpaque(true);
                this.jPanel3.add(etiqueta);
            }else{
                if(colores.get(memoria[i])!= null){
                    int [] tempColor = colores.get(memoria[i]);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel3.add(etiqueta);
                }else{
                    int tempColor[] = generateColor();
                    colores.put(memoria[i], tempColor);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel3.add(etiqueta);
                }
            }
            
        }
        this.jPanel3.updateUI();
         this.jPanel3.repaint();
        
    }
    
    
    public void buddy_system(Admin_WorstFit worstFit){
        this.jPanel4.removeAll();
        int memoria[]= worstFit.getMemoria();
        for (int i = 0; i < memoria.length; i++) {
            if (memoria[i]== -1) {
                JLabel etiqueta=new JLabel();
                etiqueta.setHorizontalAlignment(JLabel.CENTER);
                etiqueta.setBackground(Color.white);
                etiqueta.setOpaque(true);
                this.jPanel4.add(etiqueta);
            }else{
                if(colores.get(memoria[i])!= null){
                    int [] tempColor = colores.get(memoria[i]);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel4.add(etiqueta);
                }else{
                    int tempColor[] = generateColor();
                    colores.put(memoria[i], tempColor);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel4.add(etiqueta);
                }
            }
            
        }
        this.jPanel4.updateUI();
         this.jPanel4.repaint();
    }
    
    public int[] generateColor(){
        int max = 255;
        int min = 0;
        int range = max - min + 1;
        int rgb [] = new int [3]; 
        for (int i = 0; i < 3; i++) {
            rgb[i]= (int)(Math.random() * range) + min;
        }
        
    return rgb;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        });
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
