/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.Admin_BestFit;
import Clases.Admin_BuddySystem.Arbol;
import Clases.Admin_FirstFit;
import Clases.Admin_WorstFit;
import Controlador.Controlador;
import java.awt.Color;
import javax.swing.JLabel;
import java.util.HashMap; // import the HashMap class
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author josep
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    HashMap<Integer, int[]> colores;
    Controlador controler;
    public GUI() throws InterruptedException {
        initComponents();
        colores = new HashMap<Integer, int[]>();
        controler = new Controlador();
        controler.start();
            new Thread(){
        @Override
        public void run() {
                inicio();
        };
            }.start();
       //run();
        
        
        //bestFit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane2.setViewportView(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane3.setViewportView(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane4.setViewportView(jPanel4);

        jLabel1.setText("BestFit");

        jLabel2.setText("FirstFit");

        jLabel3.setText("WorstFit");

        jLabel4.setText("Buddy System");

        jLabel5.setText("Memoria D");

        jLabel6.setText("Memoria D");

        jLabel7.setText("Memoria D");

        jLabel8.setText("Memoria D");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel11.setText("jLabel11");

        jLabel12.setText("jLabel12");

        jLabel13.setText("Segmentos D");

        jLabel14.setText("Segmentos D");

        jLabel15.setText("Segmentos D");

        jLabel16.setText("Segmentos D");

        jLabel17.setText("jLabel17");

        jLabel18.setText("jLabel18");

        jLabel19.setText("jLabel19");

        jLabel20.setText("jLabel20");

        jLabel21.setText("Rechazados");

        jLabel22.setText("Rechazados");

        jLabel23.setText("Rechazados");

        jLabel24.setText("Rechazados");

        jLabel25.setText("jLabel25");

        jLabel26.setText("jLabel26");

        jLabel27.setText("jLabel27");

        jLabel28.setText("jLabel28");

        jLabel29.setText("MB");

        jLabel30.setText("MB");

        jLabel31.setText("MB");

        jLabel32.setText("MB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel28))
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void inicio(){
        
  
        while(true){
            try {
                TimeUnit.SECONDS.sleep(1);
            } catch (InterruptedException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            bestFit(this.controler.getBestFit());
            firstFit(this.controler.getFirstFit());
            worstFit(this.controler.getWorstFit());
            buddy_system(this.controler.getBuddySystem());
        }
    
    }
    
    
    
    public  void bestFit(Admin_BestFit bestFit){
        this.jPanel1.removeAll();
        this.jLabel25.setText(String.valueOf(bestFit.getRechazados().size()));
        this.jLabel9.setText(String.valueOf(bestFit.getMemoriaDisponible()));
        this.jLabel17.setText(String.valueOf(bestFit.getBloqueMemoria().size()));
        int memoria[]=bestFit.getMemoria();
        
        for (int i = 0; i < memoria.length; i++) {
            if (memoria[i]== -1) {
                JLabel etiqueta=new JLabel();
                etiqueta.setHorizontalAlignment(JLabel.CENTER);
                etiqueta.setBackground(Color.white);
                etiqueta.setOpaque(true);
                this.jPanel1.add(etiqueta);
            }else{
                if(colores.get(memoria[i])!= null){
                    int [] tempColor = colores.get(memoria[i]);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel1.add(etiqueta);
                }else{
                    int tempColor[] = generateColor();
                    colores.put(memoria[i], tempColor);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel1.add(etiqueta);
                }
            }
            
        }
        this.jPanel1.updateUI();
        this.jPanel1.repaint();
    }
    
    
    
    
    public void firstFit(Admin_FirstFit firstFit){
        this.jPanel2.removeAll();
        this.jLabel26.setText(String.valueOf(firstFit.getRechazados().size()));
        this.jLabel10.setText(String.valueOf(firstFit.getMemoriaDisponible()));
        this.jLabel18.setText(String.valueOf(firstFit.getBloqueMemoria().size()));
        int memoria[]=firstFit.getMemoria();
        for (int i = 0; i < memoria.length; i++) {
            if (memoria[i]== -1) {
                JLabel etiqueta=new JLabel();
                etiqueta.setHorizontalAlignment(JLabel.CENTER);
                etiqueta.setBackground(Color.white);
                etiqueta.setOpaque(true);
                this.jPanel2.add(etiqueta);
            }else{
                if(colores.get(memoria[i])!= null){
                    int [] tempColor = colores.get(memoria[i]);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel2.add(etiqueta);
                }else{
                    int tempColor[] = generateColor();
                    colores.put(memoria[i], tempColor);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel2.add(etiqueta);
                }
            }
            
        }
        this.jPanel2.updateUI();
         this.jPanel2.repaint();
    }
    
    
    
    
    public void worstFit(Admin_WorstFit worstFit){
        this.jPanel3.removeAll();
        int memoria[]= worstFit.getMemoria();
        this.jLabel27.setText(String.valueOf(worstFit.getRechazados().size()));
        this.jLabel11.setText(String.valueOf(worstFit.getMemoriaDisponible()));
        this.jLabel19.setText(String.valueOf(worstFit.getBloqueMemoria().size()));
        for (int i = 0; i < memoria.length; i++) {
            if (memoria[i]== -1) {
                JLabel etiqueta=new JLabel();
                etiqueta.setHorizontalAlignment(JLabel.CENTER);
                etiqueta.setBackground(Color.white);
                etiqueta.setOpaque(true);
                this.jPanel3.add(etiqueta);
            }else{
                if(colores.get(memoria[i])!= null){
                    int [] tempColor = colores.get(memoria[i]);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel3.add(etiqueta);
                }else{
                    int tempColor[] = generateColor();
                    colores.put(memoria[i], tempColor);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel3.add(etiqueta);
                }
            }
            
        }
        this.jPanel3.updateUI();
         this.jPanel3.repaint();
        
    }
    
    public int getMemoriaDisponible(int[] memoria){
         int cont = 0;
         for (int i = 0; i < memoria.length; i++) {
             if(memoria[i]==-1){
                 cont++;
             }
         }
         return cont;
     }
    
    public void buddy_system(Arbol buddy_system){
        this.jPanel4.removeAll();
        this.jLabel28.setText(String.valueOf(buddy_system.rechazados.size()));
        this.jLabel12.setText(String.valueOf(getMemoriaDisponible(buddy_system.getMemoria())));
        this.jLabel20.setText(String.valueOf(buddy_system.getBloqueMemoria().size()));
        int memoria[]= buddy_system.getMemoria();
        for (int i = 0; i < memoria.length; i++) {
            if (memoria[i]== -1) {
                JLabel etiqueta=new JLabel();
                etiqueta.setHorizontalAlignment(JLabel.CENTER);
                etiqueta.setBackground(Color.white);
                etiqueta.setOpaque(true);
                this.jPanel4.add(etiqueta);
            }else{
                if(colores.get(memoria[i])!= null){
                    int [] tempColor = colores.get(memoria[i]);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel4.add(etiqueta);
                }else{
                    int tempColor[] = generateColor();
                    colores.put(memoria[i], tempColor);
                    JLabel etiqueta=new JLabel();
                    etiqueta.setHorizontalAlignment(JLabel.CENTER);
                    etiqueta.setBackground(new Color(tempColor[0],tempColor[1],tempColor[2]));
                    etiqueta.setOpaque(true);
                    this.jPanel4.add(etiqueta);
                }
            }
            
        }
        this.jPanel4.updateUI();
         this.jPanel4.repaint();
    }
    
    public int[] generateColor(){
        int max = 255;
        int min = 0;
        int range = max - min + 1;
        int rgb [] = new int [3]; 
        for (int i = 0; i < 3; i++) {
            rgb[i]= (int)(Math.random() * range) + min;
        }
        
    return rgb;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI().setVisible(true);
                } catch (InterruptedException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        });
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
